[build]
  command = "DEBUG=* npm run build"
  publish = ".next"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_BASE_URL = "https://aianonymizer.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/**", "node_modules/@prisma/client/**"]

[[headers]]
  for = "/logo.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
