[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && next build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_BASE_URL = "https://aianonymizer.com"
  NPM_FLAGS = "--legacy-peer-deps --force"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/.prisma/**",
    "node_modules/@prisma/client/**",
    "prisma/**"
  ]
  external_node_modules = ["@prisma/client", "prisma"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000
