[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_PUBLIC_BASE_URL = "https://aianonymizer.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
