-- Drop all tables to start fresh
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;
DROP TABLE IF EXISTS "Account" CASCADE;
DROP TABLE IF EXISTS "AdminAuditLog" CASCADE;
DROP TABLE IF EXISTS "ApiKey" CASCADE;
DROP TABLE IF EXISTS "GroqKey" CASCADE;
DROP TABLE IF EXISTS "GroqKeyPool" CASCADE;
DROP TABLE IF EXISTS "Payment" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "Subscription" CASCADE;
DROP TABLE IF EXISTS "TokenUsage" CASCADE;
DROP TABLE IF EXISTS "Usage" CASCADE;
DROP TABLE IF EXISTS "UserActivity" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- Drop enums
DROP TYPE IF EXISTS "UserStatus" CASCADE;
DROP TYPE IF EXISTS "SubscriptionTier" CASCADE;
